"""Create initial database models

Revision ID: 56e4ab959c5a
Revises: 
Create Date: 2021-05-27 13:51:28.835302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56e4ab959c5a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role")
    op.drop_index("ix_user_email", table_name="user")
    op.drop_index("ix_user_username", table_name="user")
    op.drop_table("user")
    op.drop_table("follow")
    op.drop_table("role_permission")
    op.drop_table("comment")
    op.drop_table("post")
    op.drop_table("permission")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "post",
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=128), nullable=False),
        sa.Column("body", sa.TEXT(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comment",
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("body", sa.TEXT(), nullable=False),
        sa.Column("disabled", sa.BOOLEAN(), nullable=False),
        sa.Column("post_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.INTEGER(), nullable=False),
        sa.Column("permission_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "follow",
        sa.Column("followed_id", sa.INTEGER(), nullable=False),
        sa.Column("follower_id", sa.INTEGER(), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("followed_id", "follower_id"),
    )
    op.create_table(
        "user",
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), nullable=False),
        sa.Column("username", sa.VARCHAR(length=64), nullable=False),
        sa.Column("email", sa.VARCHAR(length=128), nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=300), nullable=False),
        sa.Column("confirmed", sa.BOOLEAN(), nullable=False),
        sa.Column("location", sa.VARCHAR(length=64), nullable=True),
        sa.Column("about", sa.TEXT(), nullable=True),
        sa.Column("avatar", sa.TEXT(), nullable=True),
        sa.Column("role_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_username", "user", ["username"], unique=False)
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    op.create_table(
        "role",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###
